# Generated by Django 2.2.8 on 2020-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is a test desc'),
            preserve_default=False,
        ),
    ]
